# Generated by Django 3.2 on 2022-05-21 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zatlansone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='episode',
        ),
        migrations.AddField(
            model_name='episode',
            name='content',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='zatlansone.content'),
        ),
    ]
