# Generated by Django 3.2 on 2022-05-22 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zatlansone', '0004_auto_20220522_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='content',
        ),
        migrations.AddField(
            model_name='content',
            name='episode',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='zatlansone.episode'),
        ),
    ]
