# Generated by Django 3.2 on 2022-05-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zatlansone', '0005_auto_20220522_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
